### ISSUE TITLE
getting "WARNING: No response from station" when running on RaspberryPi

### ISSUE THREAD

**Issue by saveriogzz** [goeh/weather-collector#10]
I am getting this warning from 

```Sep 29, 2021 5:21:10 PM se.technipelago.weather.vantagepro.DownloadController execute
WARNING: No response from station```

When running the application on the raspberry pi. So far when running it on my laptop it has been working.. strange!

**Comment by goeh** [comment]
I tested on two Raspberry Pi 3. I still haven't had time to setup a RP4.
Did you enable full debug logging (see README.md) so you can see the communication?

**Comment by saveriogzz** [comment]
Yes I did

I just run it again and this are the logs:

```
Sep 29, 2021 6:02:07 PM se.technipelago.weather.vantagepro.DownloadController run
SEVERE: null
java.io.IOException: Unexpected EOF
	at se.technipelago.weather.vantagepro.AbstractController.readBytes(AbstractController.java:146)
	at se.technipelago.weather.vantagepro.AbstractController.download(AbstractController.java:349)
	at se.technipelago.weather.vantagepro.DownloadController.downloadAndSave(DownloadController.java:261)
	at se.technipelago.weather.vantagepro.DownloadController.execute(DownloadController.java:158)
	at se.technipelago.weather.vantagepro.DownloadController.run(DownloadController.java:74)
	at se.technipelago.weather.vantagepro.AbstractController.startLocal(AbstractController.java:99)
	at se.technipelago.weather.vantagepro.DownloadController.main(DownloadController.java:59)
```

it's stuck here and I cannot kill the process

**Comment by goeh** [comment]
Sounds like some kind of USB/serial communication problem. It tries to read from /dev/ttyUSB0 but no data arrives.

**Comment by saveriogzz** [comment]
I already used all the 4 Pi's ports

**Comment by saveriogzz** [comment]
I will try to use a RPi3 tomorrow and see if it's different

**Comment by saveriogzz** [comment]
Good news: on a RaspberryPi 3A+ it works!
Bad news: my project will most likely require to work on RPi4

**Comment by goeh** [comment]
Ok, thats good to know.
I'm in a very busy period right now. I did one big software release this weekend and another coming up on Wednesday. After that I can hopefully breathe and look at your PRs and investigate on my Raspberry Pi 4. I'm sorry I've been offline for a while.

**Comment by saveriogzz** [comment]
No worries of course! I just text here to keep track of progress!

**Comment by goeh** [comment]
Today I made a lots of refactoring and testing on Raspberry Pi 3 and MariaDB. I now feel confident it works ok.
Next week I will test on Raspberry Pi 4 and see how that works in my setup.

**Comment by goeh** [comment]
I've successfully tested the system on a Raspberry Pi 4 with Raspberry Pi OS Lite (Release date: May 7th 2021).
No problem at all. So maybe this issue is related to Ubuntu.

**Comment by saveriogzz** [comment]
Hey @goeh , thanks for give it a try! The Ubuntu I tried the program with was a 64bit version, maybe that's the issue.
